# Build sources.
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY . ./
WORKDIR /src/src/Money.Api
RUN dotnet publish -c Release -r linux-arm -o /app

# Final image.
FROM mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim-arm32v7
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["./Money.Api"]