# Build sources.
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY . ./
WORKDIR /src/src/Money.Api
RUN dotnet publish -c Release -r linux-arm -o /app

# Final image.
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim-arm32v7
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["./Money.Api"]